// <auto-generated />
using System;
using movies_api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace movies_api.Migrations {
    [DbContext (typeof (APIContext))]
    [Migration ("20220716151317_AddMovie")]
    partial class AddMovie {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ProductVersion", "6.0.7")
                .HasAnnotation ("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns (modelBuilder, 1L, 1);

            modelBuilder.Entity ("movies_api.Models.Actor", b => {
                b.Property<int> ("id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn (b.Property<int> ("id"), 1L, 1);

                b.Property<int> ("age")
                    .HasColumnType ("int");

                b.Property<string> ("poster")
                    .HasColumnType ("nvarchar(max)");

                b.Property<DateTime> ("release_date")
                    .HasColumnType ("datetime2");

                b.Property<string> ("title")
                    .HasColumnType ("nvarchar(max)");

                b.HasKey ("id");

                b.ToTable ("Actors");
            });
#pragma warning restore 612, 618
        }
    }
}